#!/usr/bin/env php

<?php

$stdin = fopen("php://stdin", "r");

echo "🛠️  Initializing CWD Laravel Kit..." . PHP_EOL;

// Early exit check
if (!file_exists('artisan') || !file_exists('composer.json')) {
    echo "❌ Error: This script must be run from the root of a Laravel project." . PHP_EOL;
    exit(1);
}

// Step 1: Copy .env if not exists
if (!file_exists('.env')) {
    if (copy('.env.example', '.env')) {
        echo "✅ .env created" . PHP_EOL;
    } else {
        echo "❌ Failed to create .env" . PHP_EOL;
    }
}

// Step 1.5: Ask if NativePHP will be used
echo "❓ Do you want to use NativePHP? (y/N): ";
$line = strtolower(trim(fgets($stdin)));

if ($line === 'y') {
    echo "🧱 Adding NativePHP requirement..." . PHP_EOL;
    passthru('composer require nativephp/desktop -W');
    passthru('php artisan native:install');
}

// Step 2: Run composer install
echo "📦 Running composer install..." . PHP_EOL;
passthru('composer install');

// Step 3: Run npm install
echo "📦 Running npm install..." . PHP_EOL;
passthru('npm install');
echo "📦 Updating modules..." . PHP_EOL;
passthru('npm update');

// Step 4: Generate app key
echo "🔑 Generating app key..." . PHP_EOL;
passthru('php artisan key:generate');

// Step 5: Storage Linkage
echo "Linking storage" . PHP_EOL;
passthru('php artisan storage:link');

// Optional: Run migrations
echo PHP_EOL . "❓ Run database migrations w/ initial seeding? (y/N): ";
$line = strtolower(trim(fgets($stdin)));
if ($line === 'y') {
    echo "🧱 Running migrations..." . PHP_EOL;
    passthru('php artisan migrate --seed');
}

fclose($stdin);

echo "✅ Initialization complete." . PHP_EOL;
